[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zephyon_protocol = "GJXMamA3otLDQPbfzSZPeNhvzDBdeL1QhafsveKvwL2W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/zeranova/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
