#![allow(clippy::result_large_err)]

use anchor_lang::prelude::*;

pub mod errors;
pub mod events;
pub mod instructions;
pub mod state;

declare_id!("7Huo5pfufAtTyPufiZ9XZGcRLHZyPcnbsjyCDYk8G8iB");

// Re-export instruction context types so #[program] can reference them cleanly.
use crate::instructions::{
    InitializeTreasury,
    SetTreasuryPaused,
    SplDeposit,
    SplDepositWithReceipt,
    SplWithdraw,
    SplWithdrawWithReceipt,
    SplPay,
};

// --- Anchor macro bridge (crate-private) ---
// Bring the generated client account modules up to crate root.
// (These names are generated by Anchor from #[derive(Accounts)].)
pub(crate) use instructions::initialize_treasury::__client_accounts_initialize_treasury;
pub(crate) use instructions::set_treasury_paused::__client_accounts_set_treasury_paused;
pub(crate) use instructions::spl_deposit::__client_accounts_spl_deposit;
pub(crate) use instructions::spl_deposit_with_receipt::__client_accounts_spl_deposit_with_receipt;
pub(crate) use instructions::spl_withdraw::__client_accounts_spl_withdraw;
pub(crate) use instructions::spl_withdraw_with_receipt::__client_accounts_spl_withdraw_with_receipt;
pub(crate) use instructions::spl_pay::__client_accounts_spl_pay;

// Anchor 0.32+ expects this exact module name at crate root in some layouts.
#[allow(non_snake_case)]
pub mod __client_accounts_crate {
    pub use super::__client_accounts_initialize_treasury::*;
    pub use super::__client_accounts_set_treasury_paused::*;
    pub use super::__client_accounts_spl_deposit::*;
    pub use super::__client_accounts_spl_deposit_with_receipt::*;
    pub use super::__client_accounts_spl_withdraw::*;
    pub use super::__client_accounts_spl_withdraw_with_receipt::*;
    pub use super::__client_accounts_spl_pay::*;
}

#[program]
pub mod protocol {
    use super::*;

    pub fn initialize_treasury(ctx: Context<InitializeTreasury>) -> Result<()> {
        instructions::initialize_treasury::handler(ctx)
    }

    pub fn set_treasury_paused(ctx: Context<SetTreasuryPaused>, paused: bool) -> Result<()> {
        instructions::set_treasury_paused::handler(ctx, paused)
    }

    pub fn spl_deposit(ctx: Context<SplDeposit>, amount: u64) -> Result<()> {
        instructions::spl_deposit::handler(ctx, amount)
    }

    pub fn spl_deposit_with_receipt(
        ctx: Context<SplDepositWithReceipt>,
        amount: u64,
        nonce: u64,
    ) -> Result<()> {
        instructions::spl_deposit_with_receipt::handler(ctx, amount, nonce)
    }

    pub fn spl_withdraw(ctx: Context<SplWithdraw>, amount: u64) -> Result<()> {
        instructions::spl_withdraw::handler(ctx, amount)
    }

    pub fn spl_withdraw_with_receipt(
        ctx: Context<SplWithdrawWithReceipt>,
        amount: u64,
    ) -> Result<()> {
        instructions::spl_withdraw_with_receipt::handler(ctx, amount)
    }

    pub fn spl_pay(ctx: Context<SplPay>, amount: u64) -> Result<()> {
        instructions::spl_pay::handler(ctx, amount)
    }
}

